apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVQ2dpU1c3aUJKS2hETzg2bmZMZUZhQkUzMWxnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01NVEF1TVRVeUxqRTRNeTR4TUI0WERUSXlNRE13TXpFeU16a3dPVm9YRFRNeQpNREl5T1RFeU16a3dPVm93RnpFVk1CTUdBMVVFQXd3TU1UQXVNVFV5TGpFNE15NHhNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6ME1qd3VGWEZORm1BdElZbGJiam9zWTUwVjVCMUlLcVRvcnYKR3dJQnVMazhlZzNFMjVibkRKbXlaUU5uVlViVmRybEVnUkdBOU85YjhnSUdGMGpqT0kzSFZ0YTIxaHZaYnFnSgovOGNld3BrNlNKUy81M04xL2tWbUl4Y3ZDbXZCVFpRNno3QmVNM2ZBLzFQRXdGdDZjdG9NNVE5b0U5eFVPMExDCjVHSE9COU55L2RONm5DOG1iMXI2ajZ5cFlxSkdZRW1HMVRqQ3NjRkRxNHpqQ2FrS2h3VkZ3MDlLRXBxOGtrdFoKeHJscXh5dVVSYWhHTHJuZWZ0Z0dRTzFBS1hvYmxIL01IcDBhOG1HdU9KZmZGV1czVXloVnFwUndUKytxV2lIMApCcTRESTRPclJ3NVduekJTOGdwaW1KVWthYnRnejVKd2dkUjVLeHlxTEtwWDhPVWZPUUlEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVWlseGZ3ZGhodzJxOVNWOHRleC8rYkNlRmp3Z3dId1lEVlIwakJCZ3dGb0FVaWx4ZndkaGgKdzJxOVNWOHRleC8rYkNlRmp3Z3dEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBV2EvdXFrVGlSWG8vd05JellhZXFIczlFV1dPcUgzWVlYTWpGa3hUQTAvcmxOdGk0dGlVc29PcmM4djJVCnFrK3VJb0ozT0ZCYkp4TlBRbjVnNElUbVROUXFZUUVwbnFUWXBoMUdwUi9XcDNJcFhYY2pjQ29hT2ZyTi92bHMKQnhyTTM4TDlicmYyMWpzZWRLOVJhS2xHMnJ4cTBqRERZNWw4RzJDL3d2Q0pkNFUvTlVUdHJsRjhuR1h4RzNDVwpOTjkyeCt5N0w3OUdiWmUvK25ON3FTRUhVSGtTMlYzT0dSTDF6eURuNllYUTFzUWpycWpXd2c2YWVJZUNtU3NqCjZyeUhiMlFXRzBpcUpYa1dLcURsVFRFdjZHd3FKT2MwM3RpL3dhNm1YZW5WMzlIekk0Tno1UmltK2V3ZVIwZ0gKN25PVDF6cnFXZ1VvbFFBK0pUNUF5bFpOYkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://141.94.253.117:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: d3JBUzRiWk5LOEpqZjlUL0hlZTI4bVFLTmdSVE0wNXVmN3ErdmVFRDVYVT0K
